@echo off
rem START or STOP Services
rem ----------------------------------
rem Check if argument is STOP or START

if not ""%1"" == ""START"" goto stop

if exist C:\Users\Cristian\Documents\Java\Programacion Avanzada\Corte 1\Proyecto-Programacion\Poryecto-Final-Corte-1\ChicasMagicas\Base-De-Datos\hypersonic\scripts\ctl.bat (start /MIN /B C:\Users\Cristian\Documents\Java\Programacion Avanzada\Corte 1\Proyecto-Programacion\Poryecto-Final-Corte-1\ChicasMagicas\Base-De-Datos\server\hsql-sample-database\scripts\ctl.bat START)
if exist C:\Users\Cristian\Documents\Java\Programacion Avanzada\Corte 1\Proyecto-Programacion\Poryecto-Final-Corte-1\ChicasMagicas\Base-De-Datos\ingres\scripts\ctl.bat (start /MIN /B C:\Users\Cristian\Documents\Java\Programacion Avanzada\Corte 1\Proyecto-Programacion\Poryecto-Final-Corte-1\ChicasMagicas\Base-De-Datos\ingres\scripts\ctl.bat START)
if exist C:\Users\Cristian\Documents\Java\Programacion Avanzada\Corte 1\Proyecto-Programacion\Poryecto-Final-Corte-1\ChicasMagicas\Base-De-Datos\mysql\scripts\ctl.bat (start /MIN /B C:\Users\Cristian\Documents\Java\Programacion Avanzada\Corte 1\Proyecto-Programacion\Poryecto-Final-Corte-1\ChicasMagicas\Base-De-Datos\mysql\scripts\ctl.bat START)
if exist C:\Users\Cristian\Documents\Java\Programacion Avanzada\Corte 1\Proyecto-Programacion\Poryecto-Final-Corte-1\ChicasMagicas\Base-De-Datos\postgresql\scripts\ctl.bat (start /MIN /B C:\Users\Cristian\Documents\Java\Programacion Avanzada\Corte 1\Proyecto-Programacion\Poryecto-Final-Corte-1\ChicasMagicas\Base-De-Datos\postgresql\scripts\ctl.bat START)
if exist C:\Users\Cristian\Documents\Java\Programacion Avanzada\Corte 1\Proyecto-Programacion\Poryecto-Final-Corte-1\ChicasMagicas\Base-De-Datos\apache\scripts\ctl.bat (start /MIN /B C:\Users\Cristian\Documents\Java\Programacion Avanzada\Corte 1\Proyecto-Programacion\Poryecto-Final-Corte-1\ChicasMagicas\Base-De-Datos\apache\scripts\ctl.bat START)
if exist C:\Users\Cristian\Documents\Java\Programacion Avanzada\Corte 1\Proyecto-Programacion\Poryecto-Final-Corte-1\ChicasMagicas\Base-De-Datos\openoffice\scripts\ctl.bat (start /MIN /B C:\Users\Cristian\Documents\Java\Programacion Avanzada\Corte 1\Proyecto-Programacion\Poryecto-Final-Corte-1\ChicasMagicas\Base-De-Datos\openoffice\scripts\ctl.bat START)
if exist C:\Users\Cristian\Documents\Java\Programacion Avanzada\Corte 1\Proyecto-Programacion\Poryecto-Final-Corte-1\ChicasMagicas\Base-De-Datos\apache-tomcat\scripts\ctl.bat (start /MIN /B C:\Users\Cristian\Documents\Java\Programacion Avanzada\Corte 1\Proyecto-Programacion\Poryecto-Final-Corte-1\ChicasMagicas\Base-De-Datos\apache-tomcat\scripts\ctl.bat START)
if exist C:\Users\Cristian\Documents\Java\Programacion Avanzada\Corte 1\Proyecto-Programacion\Poryecto-Final-Corte-1\ChicasMagicas\Base-De-Datos\resin\scripts\ctl.bat (start /MIN /B C:\Users\Cristian\Documents\Java\Programacion Avanzada\Corte 1\Proyecto-Programacion\Poryecto-Final-Corte-1\ChicasMagicas\Base-De-Datos\resin\scripts\ctl.bat START)
if exist C:\Users\Cristian\Documents\Java\Programacion Avanzada\Corte 1\Proyecto-Programacion\Poryecto-Final-Corte-1\ChicasMagicas\Base-De-Datos\jetty\scripts\ctl.bat (start /MIN /B C:\Users\Cristian\Documents\Java\Programacion Avanzada\Corte 1\Proyecto-Programacion\Poryecto-Final-Corte-1\ChicasMagicas\Base-De-Datos\jetty\scripts\ctl.bat START)
if exist C:\Users\Cristian\Documents\Java\Programacion Avanzada\Corte 1\Proyecto-Programacion\Poryecto-Final-Corte-1\ChicasMagicas\Base-De-Datos\subversion\scripts\ctl.bat (start /MIN /B C:\Users\Cristian\Documents\Java\Programacion Avanzada\Corte 1\Proyecto-Programacion\Poryecto-Final-Corte-1\ChicasMagicas\Base-De-Datos\subversion\scripts\ctl.bat START)
rem RUBY_APPLICATION_START
if exist C:\Users\Cristian\Documents\Java\Programacion Avanzada\Corte 1\Proyecto-Programacion\Poryecto-Final-Corte-1\ChicasMagicas\Base-De-Datos\lucene\scripts\ctl.bat (start /MIN /B C:\Users\Cristian\Documents\Java\Programacion Avanzada\Corte 1\Proyecto-Programacion\Poryecto-Final-Corte-1\ChicasMagicas\Base-De-Datos\lucene\scripts\ctl.bat START)
if exist C:\Users\Cristian\Documents\Java\Programacion Avanzada\Corte 1\Proyecto-Programacion\Poryecto-Final-Corte-1\ChicasMagicas\Base-De-Datos\third_application\scripts\ctl.bat (start /MIN /B C:\Users\Cristian\Documents\Java\Programacion Avanzada\Corte 1\Proyecto-Programacion\Poryecto-Final-Corte-1\ChicasMagicas\Base-De-Datos\third_application\scripts\ctl.bat START)
goto end

:stop
echo "Stopping services ..."
if exist C:\Users\Cristian\Documents\Java\Programacion Avanzada\Corte 1\Proyecto-Programacion\Poryecto-Final-Corte-1\ChicasMagicas\Base-De-Datos\third_application\scripts\ctl.bat (start /MIN /B C:\Users\Cristian\Documents\Java\Programacion Avanzada\Corte 1\Proyecto-Programacion\Poryecto-Final-Corte-1\ChicasMagicas\Base-De-Datos\third_application\scripts\ctl.bat STOP)
if exist C:\Users\Cristian\Documents\Java\Programacion Avanzada\Corte 1\Proyecto-Programacion\Poryecto-Final-Corte-1\ChicasMagicas\Base-De-Datos\lucene\scripts\ctl.bat (start /MIN /B C:\Users\Cristian\Documents\Java\Programacion Avanzada\Corte 1\Proyecto-Programacion\Poryecto-Final-Corte-1\ChicasMagicas\Base-De-Datos\lucene\scripts\ctl.bat STOP)
rem RUBY_APPLICATION_STOP
if exist C:\Users\Cristian\Documents\Java\Programacion Avanzada\Corte 1\Proyecto-Programacion\Poryecto-Final-Corte-1\ChicasMagicas\Base-De-Datos\subversion\scripts\ctl.bat (start /MIN /B C:\Users\Cristian\Documents\Java\Programacion Avanzada\Corte 1\Proyecto-Programacion\Poryecto-Final-Corte-1\ChicasMagicas\Base-De-Datos\subversion\scripts\ctl.bat STOP)
if exist C:\Users\Cristian\Documents\Java\Programacion Avanzada\Corte 1\Proyecto-Programacion\Poryecto-Final-Corte-1\ChicasMagicas\Base-De-Datos\jetty\scripts\ctl.bat (start /MIN /B C:\Users\Cristian\Documents\Java\Programacion Avanzada\Corte 1\Proyecto-Programacion\Poryecto-Final-Corte-1\ChicasMagicas\Base-De-Datos\jetty\scripts\ctl.bat STOP)
if exist C:\Users\Cristian\Documents\Java\Programacion Avanzada\Corte 1\Proyecto-Programacion\Poryecto-Final-Corte-1\ChicasMagicas\Base-De-Datos\hypersonic\scripts\ctl.bat (start /MIN /B C:\Users\Cristian\Documents\Java\Programacion Avanzada\Corte 1\Proyecto-Programacion\Poryecto-Final-Corte-1\ChicasMagicas\Base-De-Datos\server\hsql-sample-database\scripts\ctl.bat STOP)
if exist C:\Users\Cristian\Documents\Java\Programacion Avanzada\Corte 1\Proyecto-Programacion\Poryecto-Final-Corte-1\ChicasMagicas\Base-De-Datos\resin\scripts\ctl.bat (start /MIN /B C:\Users\Cristian\Documents\Java\Programacion Avanzada\Corte 1\Proyecto-Programacion\Poryecto-Final-Corte-1\ChicasMagicas\Base-De-Datos\resin\scripts\ctl.bat STOP)
if exist C:\Users\Cristian\Documents\Java\Programacion Avanzada\Corte 1\Proyecto-Programacion\Poryecto-Final-Corte-1\ChicasMagicas\Base-De-Datos\apache-tomcat\scripts\ctl.bat (start /MIN /B /WAIT C:\Users\Cristian\Documents\Java\Programacion Avanzada\Corte 1\Proyecto-Programacion\Poryecto-Final-Corte-1\ChicasMagicas\Base-De-Datos\apache-tomcat\scripts\ctl.bat STOP)
if exist C:\Users\Cristian\Documents\Java\Programacion Avanzada\Corte 1\Proyecto-Programacion\Poryecto-Final-Corte-1\ChicasMagicas\Base-De-Datos\openoffice\scripts\ctl.bat (start /MIN /B C:\Users\Cristian\Documents\Java\Programacion Avanzada\Corte 1\Proyecto-Programacion\Poryecto-Final-Corte-1\ChicasMagicas\Base-De-Datos\openoffice\scripts\ctl.bat STOP)
if exist C:\Users\Cristian\Documents\Java\Programacion Avanzada\Corte 1\Proyecto-Programacion\Poryecto-Final-Corte-1\ChicasMagicas\Base-De-Datos\apache\scripts\ctl.bat (start /MIN /B C:\Users\Cristian\Documents\Java\Programacion Avanzada\Corte 1\Proyecto-Programacion\Poryecto-Final-Corte-1\ChicasMagicas\Base-De-Datos\apache\scripts\ctl.bat STOP)
if exist C:\Users\Cristian\Documents\Java\Programacion Avanzada\Corte 1\Proyecto-Programacion\Poryecto-Final-Corte-1\ChicasMagicas\Base-De-Datos\ingres\scripts\ctl.bat (start /MIN /B C:\Users\Cristian\Documents\Java\Programacion Avanzada\Corte 1\Proyecto-Programacion\Poryecto-Final-Corte-1\ChicasMagicas\Base-De-Datos\ingres\scripts\ctl.bat STOP)
if exist C:\Users\Cristian\Documents\Java\Programacion Avanzada\Corte 1\Proyecto-Programacion\Poryecto-Final-Corte-1\ChicasMagicas\Base-De-Datos\mysql\scripts\ctl.bat (start /MIN /B C:\Users\Cristian\Documents\Java\Programacion Avanzada\Corte 1\Proyecto-Programacion\Poryecto-Final-Corte-1\ChicasMagicas\Base-De-Datos\mysql\scripts\ctl.bat STOP)
if exist C:\Users\Cristian\Documents\Java\Programacion Avanzada\Corte 1\Proyecto-Programacion\Poryecto-Final-Corte-1\ChicasMagicas\Base-De-Datos\postgresql\scripts\ctl.bat (start /MIN /B C:\Users\Cristian\Documents\Java\Programacion Avanzada\Corte 1\Proyecto-Programacion\Poryecto-Final-Corte-1\ChicasMagicas\Base-De-Datos\postgresql\scripts\ctl.bat STOP)

:end

